Fix detect_error() so that it ignores NOTICE. Without this following error occurs, for example:
BEGIN;
BEGIN;

ERROR:  kind mismatch among backends 0[N] 1[E]