Fix the following bugs in master_slave mode && load_balance mode.
1.
We force to replicate PREPARE and DEALLOCATE statement because of the case.

  PREPARE xx AS SELECT 1;
  EXECUTE xx;

If EXECUTE statement was load balanced, it occured the error.

  ERROR:  prepared statement "xx" does not exist

2.
pgpool didn't load balance a SELECT query using extended protocol.